version: '3.7'

x-labels:
  labels: &default-label
    mssql:

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    labels: *default-label
    restart: always
    ports: 
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql
    env_file:
      - .env
    environment:
      ## Full list:
      ## https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PWD}
      - TZ=Asia/Taipei
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=True

  jobber:
    image: blacklabelops/jobber:docker
    restart: always
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - backup:/backup
      - ./shellScript:/script:ro
    environment:
      - BACKUP_LABEL=mssql
      ## JOB number must start from 1
      - JOB_NAME1=Backup
      - JOB_COMMAND1=/bin/bash /script/backup.sh
      - JOB_TIME1=0 0 0 * * 6 #Exec per Week at UTC Sat. 0 a.m.
      - JOB_NOTIFY_ERR1=true
      - JOB_NOTIFY_FAIL1=true
      # - JOB_NAME1=Restore
      # - JOB_COMMAND1=/bin/bash /script/restore.sh
      # - JOB_TIME1=0 0 0 * * 6 #Exec per Week at UTC Sat. 0 a.m.
      # - JOB_NOTIFY_ERR1=true
      # - JOB_NOTIFY_FAIL1=true

volumes:
  mssql:
    labels: *default-label
  backup:
    driver_opts:
      type: cifs
      o: ${CIFS_OPTION}
      device: ${BACKUP_FOLDER}
