version: '3.7'

x-labels:
  labels: &default-label
    mssql:

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    labels: *default-label
    restart: always
    ports: 
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PWD}
      - TZ=Asia/Taipei
      - MSSQL_PID=Developer

  jobber:
    image: blacklabelops/jobber:docker
    restart: always
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${BACKUP_FOLDER}:/backup
      - ./shellScript:/script:ro
    environment:
      - JOB_NAME1=Backup
      - JOB_COMMAND1=/bin/bash /script/backup.sh
      - JOB_TIME1=0 0 0 * * 6 #Exec per Week at UTC Sat. 0 a.m.
      - JOB_NOTIFY_ERR1=true
      - JOB_NOTIFY_FAIL1=true
      - BACKUP_LABEL=mssql

volumes:
  mssql:
    labels: *default-label
