version: '3.7'

x-labels:
  labels: &default-label
    mssql:

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    labels: *default-label
    restart: always
    ports: 
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql
    env_file:
      - .env
    environment:
      ## Full list:
      ## https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PWD}
      - TZ=Asia/Taipei
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=True

  backup:
    build: ./volume-backup
    restart: "no"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - mssql:/volume:ro
      - backup:/backup
    environment:
      - BACKUP_LABEL=mssql
    command: ./backup.sh
    network_mode: none

  # restore:
  #   build: ./volume-backup
  #   restart: "no"
  #   env_file:
  #     - .env
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - mssql:/volume 
  #     - backup:/backup
  #   environment:
  #     - BACKUP_LABEL=mssql
  #   command: ./restore.sh
  #   network_mode: none

volumes:
  mssql:
    labels: *default-label
    ## If you encounter different volume names during backup/restore, please declare the name here.
    # name: docker-mssql-server_mssql
  backup:
    driver_opts:
      type: cifs
      o: ${CIFS_OPTION}
      device: ${BACKUP_FOLDER}
