version: '3.7'

x-labels:
  labels: &default-label
    mssql:

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    labels: *default-label
    restart: always
    ports: 
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql
    env_file:
      - .env
    environment:
      ## Full list:
      ## https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PWD}
      - TZ=Asia/Taipei
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=True

  jobber:
    image: blacklabelops/jobber:docker
    restart: always
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./:/docker-compose:ro
    environment:
      ## JOB number must start from 1
      - JOB_NAME1=DoJob
      - JOB_COMMAND1=/bin/bash cd /docker-compose && docker-compose start backup
      - JOB_TIME1=0 0 0 * * 6 #Exec per Week at UTC Sat. 0 a.m.
      - JOB_NOTIFY_ERR1=true
      - JOB_NOTIFY_FAIL1=true

  backup:
    build: ./volume-backup
    restart: "no"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - mssql:/volume:ro
      - ${BACKUP_FOLDER}:/backup
    environment:
      - BACKUP_LABEL=mssql
    command: ./backup.sh
    network_mode: none

  # restore:
  #   build: ./volume-backup
  #   restart: "no"
  #   env_file:
  #     - .env
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - mssql:/volume 
  #     - ${BACKUP_FOLDER}:/backup:ro
  #   environment:
  #     - BACKUP_LABEL=mssql
  #   command: ./restore.sh
  #   network_mode: none

volumes:
  mssql:
    labels: *default-label
    ## If you encounter different volume names during backup/restore, please declare the name here.
    # name: docker-mssql-server_mssql
